-- [[ Setup ]]
require('conf.theme')
require('conf.nvim-tree')
require('conf.lualine')
require('conf.nvim-autopairs')
require('conf.indent-blankline')
require('conf.telescope')
require('conf.tree-sitter')
require('conf.nvim-lspconfig')
require('conf.copilot')
require('conf.luasnip')
require('conf.nvim-cmp')
